assets:
  - token.sh
steps:
  - name: Download terminus
    command: 'curl https://github.com/pantheon-systems/terminus/releases/download/0.11.0/terminus.phar -L -o $HOME/terminus && chmod +x $HOME/terminus'
  - name: Login to terminus
    command: 'source $ASSET_DIR/token.sh ; $HOME/terminus auth login --machine-token=$PANTHEON_TOKEN'
  - name: Download node script.
    command: wget -q https://deb.nodesource.com/setup_4.x
  - name: set right permissions.
    command: chmod +x setup_4.x
  - name: Execute node script.
    command: ./setup_4.x
  - name: Delete node script.
    command: rm setup_4.x
  - name: Install node.
    command: apt-get install nodejs -y
  - name: Install npm dependencies.
    command: 'cd $SRC_DIR && npm install'
  - name: Install composer dependencies.
    command: 'cd $SRC_DIR && composer install --prefer-source --no-interaction'
  - name: Copy settings.secret.php file.
    command: 'cp $SRC_DIR/probo/probo.settings.secret.php $SRC_DIR/settings/settings.secret.php'
  - name: Build site
    command: 'cd $SRC_DIR && ./node_modules/.bin/aquifer build'
  - name: Download DB
    command: '$HOME/terminus site backups get --site=nyccampdemo --env=dev --element=database --to=$ASSET_DIR/test-export.sql.gz --latest'
  - name: Setup Drupal
    plugin: Drupal
    subDirectory: build
  - name: Import DB.
    command: 'gunzip -c $ASSET_DIR/test-export.sql.gz | drush --root="$SRC_DIR/build" sqlc'
  - name: Master Enable
    command: 'drush --root="$SRC_DIR/build" en -y master'
  - name: Master Scope
    command: 'drush --root="$SRC_DIR/build" master-scope development'
  - name: Master Execute
    command: 'drush --root="$SRC_DIR/build" master-execute -y'
  - name: Updb
    command: 'drush --root="$SRC_DIR/build" updb -y'
  - name: Fra
    command: 'drush --root="$SRC_DIR/build" fra -y'
  - name: cc all
    command: 'drush --root="$SRC_DIR/build" cc all'

